<?php
 return array (
  'APP_CNT_MISSCALL_NO' => '07969104005',
  'SITE_TITLE' => 
  array (
    'default' => 'Ideal OMS',
  ),
  'ADMIN_EMAIL' => 'info@ideal.ind.in',
  'APP_CNT_WHATSAPP' => '8238074501',
  'SMS_SERVICE_PROVIDER_URL' => 'http://voice.smsbomb.online/smsstatuswithid.aspx',
  'SITE_NAME' => 
  array (
    'default' => 'Ideal OMS',
  ),
  'ADMIN_NAME' => 'Admin Ideal OMS',
  'APP_CNT_EMAIL' => 'info@ideal.ind.in',
  'SMS_SENDER_ID' => 'idealoms',
  'PHONE_FAX' => '8488881390',
  'TIME_ZONE' => 'Asia/Kolkata',
  'APP_LOCATION' => '203, 2nd Floor, 3 rd Eye- II,
Opp.Parimal Garden,
C.G. Road, Ahmedabad-380006, Gujarat, India.',
  'SMS_SENDER_MOBILE' => '8488881390',
  'ADDRESS' => '203, 2nd Floor, 3 rd Eye- II,
Opp.Parimal Garden,
C.G. Road, Ahmedabad-380006, Gujarat, India.',
  'APP_GST_NO' => '27AAECL8470G1Z9',
  'META_TITLE' => 
  array (
    'default' => 'Ideal OMS',
  ),
  'SMS_SENDER_PASSWORD' => 'Abdc@1243',
  'APP_NOTES_TITLE_MAX_LENGTH' => '300',
  'APP_TATA_CDN_URL_EXPIRY_HOURS' => '10',
  'APP_COMMUNITY_ANSWER_MAX_LENGTH' => '300',
  'APP_DASHBOARD_REVIEW_MAX_LENGTH' => '15',
  'APP_LEARNING_OUTCOME_MAX_LENGTH' => '300',
  'APP_NOTES_DESCRIPTION_MAX_LENGTH' => '1000',
  'APP_PUSH_NOTIFICATION_SEND_LIMIT' => '10',
  'APP_COMMUNITY_QUESTION_MAX_LENGTH' => '100',
  'APP_DASHBOARD_RECENT_TOPIC_MAX_LENGTH' => '15',
  'APP_DASHBOARD_PREVIOUS_TOPIC_MAX_LENGTH' => '15',
  'APP_TOPIC_REMINDER_NOTIFICATION_BEFORE_MINUTES' => '30',
  'APP_PAN_NO' => 'AAECL8470G',
  'META_KEYWORDS' => 
  array (
    'default' => '',
  ),
  'SYSTEM_EMAIL_FOOTER' => 'Regards,
Ideal OMS.',
  'SYSTEM_EMAIL_ADDRESS' => 'info@ideal.ind.in',
  'APP_INACTIVITY_REMINDER_NOTIFICATION_AFETR_DAYS' => '5',
  'ACHIEVE_CERTIFICATE_NOTIFICATION_REMINDER_AFTER_FINISH_MODULE' => '60',
  'SYSTEM_NAME' => 'Ideal OMS',
  'FACEBOOK_LINK' => 'https://www.facebook.com/IdealGetInvolved/',
  'META_DESCRIPTION' => 
  array (
    'default' => '',
  ),
  'REMOVE_NOTIFICATION_BEFORE_DAYS' => '5',
  'PAGE_LIMIT' => 'Yes',
  'APP_REC_LIMIT' => '10',
  'INSTAGRAM_LINK' => 'https://instagram.com/ideal_experiential_learning?igshid=k8fvgy0xgn8y',
  'DATETIME_FORMAT' => 'j-M-Y H:i:s A',
  'APP_COMMUNITY_ANSWER_POST' => 'ENABLE',
  'SHOW_VIDEOS_IN_FREE_TRIAL' => '3',
  'APP_COMMUNITY_QUESTION_POST' => 'ENABLE',
  'DATE_FORMAT' => 'd-M-y',
  'PASSWORD_EXPIRATION_TIME' => '30',
  'QUESTION_ANSWER_EDIT_TIME' => '60',
  'YOUTUBE_LINK' => 'https://www.youtube.com/channel/UC2Bs2wqa-jhZokdjccMJSww',
  'MEMBER_DEVICE_CHANGE_ATTEMPT' => '2',
  'APP_WEBSITE' => 'https://www.ideal.ind.in/',
  'APP_OPENER_INTRO_VIDEO_URL' => 'https://youtu.be/CkiHU4FOVXc',
  'APP_ORGANIZATION_NAME' => 'Ideal OMS',
) ;